/* 
 * CityPay POS API
 *
 * CityPay Point of Sale API for payment with card present devices including EMV readers and contactless POS readers.  The API makes it simple to add EMV and contactless card acceptance to iOS, Android, Tablet and desktop applicaitons using a HTTPS protocol. It segregates the complexity of payment processing from the sales environment and eliminates any necessity for the target system to handle card data. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@citypay.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CityPay.Pos.Api;
using CityPay.Pos.Model;
using CityPay.Pos.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CityPay.Pos.Test
{
    /// <summary>
    ///  Class for testing ReversalRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ReversalRequestTests
    {
        // TODO uncomment below to declare an instance variable for ReversalRequest
        //private ReversalRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ReversalRequest
            //instance = new ReversalRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ReversalRequest
        /// </summary>
        [Test]
        public void ReversalRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ReversalRequest
            //Assert.IsInstanceOfType<ReversalRequest> (instance, "variable 'instance' is a ReversalRequest");
        }


        /// <summary>
        /// Test the property 'Identifier'
        /// </summary>
        [Test]
        public void IdentifierTest()
        {
            // TODO unit test for the property 'Identifier'
        }

    }

}
