/* 
 * CityPay POS API
 *
 * CityPay Point of Sale API for payment with card present devices including EMV readers and contactless POS readers.  The API makes it simple to add EMV and contactless card acceptance to iOS, Android, Tablet and desktop applicaitons using a HTTPS protocol. It segregates the complexity of payment processing from the sales environment and eliminates any necessity for the target system to handle card data. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@citypay.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CityPay.Pos.Api;
using CityPay.Pos.Model;
using CityPay.Pos.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CityPay.Pos.Test
{
    /// <summary>
    ///  Class for testing SaleRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SaleRequestTests
    {
        // TODO uncomment below to declare an instance variable for SaleRequest
        //private SaleRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SaleRequest
            //instance = new SaleRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SaleRequest
        /// </summary>
        [Test]
        public void SaleRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SaleRequest
            //Assert.IsInstanceOfType<SaleRequest> (instance, "variable 'instance' is a SaleRequest");
        }


        /// <summary>
        /// Test the property 'Device'
        /// </summary>
        [Test]
        public void DeviceTest()
        {
            // TODO unit test for the property 'Device'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Test]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'Identifier'
        /// </summary>
        [Test]
        public void IdentifierTest()
        {
            // TODO unit test for the property 'Identifier'
        }

    }

}
